PREFIX gip_prop: <http://gipuzkoa.eus/prop/>
PREFIX gip: <http://gipuzkoa.eus/resource/>
PREFIX drm: <http://vocab.data.gov/def/drm#>

SELECT ?kokapena 

WHERE {
   gip:aitor-labajo drm:worksFor ?museo .
   ?museo gip_prop:kokalekua ?kokapena 
}